# Generated by Django 5.1.5 on 2026-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutblock_contactmessage_herosection_photogallery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Main section', 'verbose_name_plural': 'Main sections'},
        ),
        migrations.AlterField(
            model_name='herosection',
            name='heading',
            field=models.CharField(default='VIEW OUR WORK', max_length=100),
        ),
    ]
